# Use /etc/hosts to change the dns to 127.0.0.1, see bin/setup
APP_HOST: 'investment-tracking.dev'
APP_PORT: '3000'

# Mail config
MAIL_HOST: ''
MAIL_USERNAME: ''
MAIL_PASSWORD: ''
MAIL_SENDER: 'yourname+investment-tracking@example.com' # change your name and domain to @renuo.ch

# Redmine API-Key
REDMINE_API_KEY: 'your-redmine-api-key'

# Secrets
SECRET_KEY_BASE: 'rake secret'

# Newrelic
NEW_RELIC_LICENSE_KEY: 'TO DO'
NEW_RELIC_APP_NAME: 'investment-tracking-<branch>'

# Add 3 new projects for develop/master/testing at https://app.getsentry.com/organizations/renuo/projects/new/
SENTRY_DSN: ''
SENTRY_PUBLIC_DSN: ''
